import re


class FILTERED:
    """Class to store filtered words."""

    Blacklisted_Words: list[str] = [
        "rape",
        "nig",
        "nigerians",
        "nigga",
        "niggga",
        "nigggaa",
        "niggard",
        "niggarded",
        "niggarding",
        "niggardise",
        "niggardised",
        "niggardising",
        "niggardize",
        "niggardized",
        "niggardizing",
        "niggardly",
        "niggardliness",
        "niggardling",
        "niggardness",
        "niggards",
        "nigged",
        "nigger",
        "niggerdom",
        "niggered",
        "niggerfish",
        "niggerfishes",
        "niggergoose",
        "niggerhead",
        "niggery",
        "niggerish",
        "niggerism",
        "niggerling",
        "niggers",
        "niggertoe",
        "niggerweed",
        "nigget",
        "nigging",
        "niggle",
        "niggled",
        "niggler",
        "nigglers",
        "niggles",
        "niggly",
        "niggling",
        "nigglingly",
        "nigglings",
        "niggot",
        "niggra",
        "niggun",
        "nigh",
        "nighed",
        "nigher",
        "nighers",
        "nighing",
        "fagged",
        "fagger",
        "faggery",
        "faggy",
        "fagging",
        "faggingly",
        "faggot",
        "faggoted",
        "faggoty",
        "faggoting",
        "faggotry",
        "faggots",
        "fagin",
        "fagine",
        "fagins",
        "fagopyrism",
        "fagopyrismus",
        "fagopyrum",
        "fagot",
        "fagoted",
        "fagoter",
        "fagoters",
        "fagoty",
        "fagoting",
        "fagotings",
        "fagots",
        "fagott",
        "fagotte",
        "fagottino",
        "fagottist",
        "fagotto",
        "fagottone",
        "fags",
        "fagus" "fagot",
        "fagoted",
        "fagoter",
        "fagoters",
        "fagoty",
        "fagoting",
        "fagotings",
        "fagottone",
        "fags",
        "fagus",
        "@everyone",
        "@here",
        "bad word",
        "badword",
    ]

    Whitelisted_Words: list[str] = [
        "night",
        "knight",
    ]

    MENTION_REGEX = re.compile(
        r"<@!?(\d+)>|<@&(\d+)>|@everyone|@here",
        re.IGNORECASE,
    )

    @classmethod
    def sanitize_mentions(cls, text: str) -> str:
        """Remove all Discord mentions from text."""
        return cls.MENTION_REGEX.sub("[mention]", text)
